version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive

  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    revive:
      rules:
        - name: var-naming
        - name: exported
          disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
